# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base for building
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY src ./src

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js image for the final release
FROM node:22-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build output and package.json files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Set the environment variables (e.g., EVERART_API_KEY) as needed
# ENV EVERART_API_KEY=your_api_key_here

# Command to run the application
CMD ["node", "build/index.js"]
